# Generated by Django 5.2.7 on 2026-07-28 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('adapted_summary', models.TextField(blank=True, null=True)),
                ('adapted_experiences', models.JSONField(default=list)),
                ('adapted_certifications', models.JSONField(default=list)),
                ('adapted_education', models.JSONField(default=list)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('prompt_summary', models.TextField(blank=True, help_text='Brief note of what was adapted')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cv_versions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=False, help_text='Marked when sent to company')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_versions', to='cv_assistant.jobapplication')),
            ],
            options={
                'verbose_name': 'CV Version',
                'verbose_name_plural': 'CV Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cv_assistant.jobapplication')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cv_assistant.cvversion')),
            ],
            options={
                'verbose_name': 'Recruiter Response',
                'verbose_name_plural': 'Recruiter Responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
