# Generated by Django 5.2.7 on 2026-07-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cvversion',
            unique_together={('job_application', 'version_number')},
        ),
    ]
