# Generated by Django 5.2.7 on 2025-11-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=100)),
                ('content', models.TextField(help_text='Write your personal description in markdown format')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Project description in markdown format')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/projects/')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('live_url', models.URLField(blank=True, help_text='Live project URL', null=True)),
                ('technologies', models.CharField(help_text='Technologies used, separated by commas', max_length=500)),
                ('featured', models.BooleanField(default=False, help_text='Mark as featured project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='e.g., Programming Languages, Frameworks, Tools', max_length=50)),
                ('proficiency_level', models.IntegerField(default=50, help_text='Proficiency level from 0 to 100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', '-proficiency_level'],
            },
        ),
    ]
