# Generated by Django 5.2.7 on 2025-12-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn Profile URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter Profile URL', null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook Profile URL', null=True)),
                ('github_url', models.URLField(blank=True, help_text='GitHub Profile URL', null=True)),
            ],
            options={
                'verbose_name': 'Social Settings',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', '-created_at'], 'verbose_name': 'Project'},
        ),
    ]
