# Generated by Django 5.2.7 on 2025-12-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_socialsettings_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', '-years_of_experience'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='socialsettings',
            options={'verbose_name': 'Social Settings', 'verbose_name_plural': 'Social Settings'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency_level',
        ),
        migrations.AddField(
            model_name='skill',
            name='years_of_experience',
            field=models.IntegerField(default=1, help_text='Years of experience with this skill'),
        ),
    ]
