# Generated by Django 5.2.7 on 2025-12-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('position', models.CharField(help_text='Job title/position', max_length=200)),
                ('description', models.TextField(help_text='Job description and achievements in markdown format')),
                ('location', models.CharField(blank=True, help_text='Job location (city, country)', max_length=200, null=True)),
                ('start_date', models.DateField(help_text='Start date of employment')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave empty if current)', null=True)),
                ('current', models.BooleanField(default=False, help_text='Currently working here')),
                ('company_url', models.URLField(blank=True, help_text='Company website URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
