# Generated by Django 5.2.7 on 2025-12-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Certification or course name', max_length=200)),
                ('issuing_organization', models.CharField(help_text='Organization that issued the certification', max_length=200)),
                ('issue_date', models.DateField(help_text='Date when certification was issued')),
                ('expiry_date', models.DateField(blank=True, help_text="Expiration date (leave empty if doesn't expire)", null=True)),
                ('credential_id', models.CharField(blank=True, help_text='Credential ID or certificate number', max_length=200, null=True)),
                ('credential_url', models.URLField(blank=True, help_text='URL to verify credential', null=True)),
                ('description', models.TextField(blank=True, help_text='Brief description in markdown format', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='Educational institution name', max_length=200)),
                ('degree', models.CharField(help_text='Degree or diploma obtained', max_length=200)),
                ('field_of_study', models.CharField(help_text='Major or field of study', max_length=200)),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave empty if current)', null=True)),
                ('current', models.BooleanField(default=False, help_text='Currently studying here')),
                ('grade', models.CharField(blank=True, help_text="GPA or grade (e.g., '3.8/4.0', 'First Class')", max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional details in markdown format', null=True)),
                ('institution_url', models.URLField(blank=True, help_text='Institution website URL', null=True)),
                ('location', models.CharField(blank=True, help_text='Institution location (city, country)', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Professional Summary', help_text='Section title', max_length=200)),
                ('content', models.TextField(help_text='Professional summary in markdown format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professional Summary',
                'verbose_name_plural': 'Professional Summary',
            },
        ),
    ]
