"""Tests for BlogPostSerializer."""
from django.test import TestCase

from apps.blog.models import BlogPost
from apps.blog.api.serializers import BlogPostSerializer


class TestBlogPostSerializer(TestCase):

    def _valid_data(self, **overrides):
        data = {
            'title': 'Test Post',
            'content': 'Some content here',
            'excerpt': 'Short summary',
            'published': False,
        }
        data.update(overrides)
        return data

    def test_valid_data_is_valid(self):
        s = BlogPostSerializer(data=self._valid_data())
        self.assertTrue(s.is_valid(), s.errors)

    def test_validate_title_rejects_empty_string(self):
        s = BlogPostSerializer(data=self._valid_data(title=''))
        self.assertFalse(s.is_valid())
        self.assertIn('title', s.errors)

    def test_validate_title_rejects_whitespace_only(self):
        s = BlogPostSerializer(data=self._valid_data(title='   '))
        self.assertFalse(s.is_valid())
        self.assertIn('title', s.errors)

    def test_validate_title_strips_whitespace(self):
        s = BlogPostSerializer(data=self._valid_data(title='  Hello  '))
        self.assertTrue(s.is_valid(), s.errors)
        self.assertEqual(s.validated_data['title'], 'Hello')

    def test_validate_title_rejects_over_200_chars(self):
        s = BlogPostSerializer(data=self._valid_data(title='x' * 201))
        self.assertFalse(s.is_valid())
        self.assertIn('title', s.errors)

    def test_validate_title_accepts_exactly_200_chars(self):
        s = BlogPostSerializer(data=self._valid_data(title='a' * 200))
        self.assertTrue(s.is_valid(), s.errors)

    def test_validate_content_rejects_empty(self):
        s = BlogPostSerializer(data=self._valid_data(content=''))
        self.assertFalse(s.is_valid())
        self.assertIn('content', s.errors)

    def test_validate_content_rejects_whitespace_only(self):
        s = BlogPostSerializer(data=self._valid_data(content='   '))
        self.assertFalse(s.is_valid())
        self.assertIn('content', s.errors)

    def test_validate_content_strips(self):
        s = BlogPostSerializer(data=self._valid_data(content='  hello  '))
        self.assertTrue(s.is_valid(), s.errors)
        self.assertEqual(s.validated_data['content'], 'hello')

    def test_slug_in_payload_ignored_autogenerated_from_title(self):
        data = self._valid_data(title='My Post')
        data['slug'] = 'custom-slug'
        s = BlogPostSerializer(data=data)
        self.assertTrue(s.is_valid(), s.errors)
        post = s.save()
        # slug is read-only in the serializer; model auto-generates from title
        self.assertNotEqual(post.slug, 'custom-slug')
        self.assertEqual(post.slug, 'my-post')

    def test_create_increments_count(self):
        s = BlogPostSerializer(data=self._valid_data())
        self.assertTrue(s.is_valid(), s.errors)
        s.save()
        self.assertEqual(BlogPost.objects.count(), 1)

    def test_update_changes_title(self):
        post = BlogPost.objects.create(title='Original', content='test')
        s = BlogPostSerializer(post, data={'title': 'Updated'}, partial=True)
        self.assertTrue(s.is_valid(), s.errors)
        updated_post = s.save()
        self.assertEqual(updated_post.title, 'Updated')

    def test_read_only_fields_not_in_validated_data(self):
        data = self._valid_data()
        data.update({'id': 999, 'slug': 'injected', 'created_at': '2020-01-01T00:00:00Z'})
        s = BlogPostSerializer(data=data)
        self.assertTrue(s.is_valid(), s.errors)
        for field in ('id', 'slug', 'created_at', 'updated_at', 'published_at'):
            self.assertNotIn(field, s.validated_data)
